export const sectionOrder = ['story', 'schedule', 'rsvp', 'faq', 'gallery']

export const occasions = [
  {
    id: 'wedding',
    label: 'Wedding',
    glyph: '∞',
    hint: 'For the forever kind',
    titleLabel: 'Your names',
    titlePlaceholder: 'Sofia & James',
    sectionLabels: {
      story: 'Our story',
      schedule: 'The day',
      rsvp: 'RSVP',
      faq: 'Good to know',
      gallery: 'Our moments',
    },
    defaults: {
      title: 'Sofia & James',
      eyebrow: 'Together with their families',
      intro: 'Invite you to celebrate their wedding',
      date: '2026-09-19',
      time: '17:00',
      venue: 'The Glasshouse',
      location: 'Nicosia, Cyprus',
      storyTitle: 'A day made for us',
      storyBody:
        'After years of shared Sundays, long roads and little adventures, we are making it official. We would love nothing more than to have you there.',
      hostOneLabel: "Sofia's family",
      hostOne: 'The Marin family',
      hostTwoLabel: "James's family",
      hostTwo: 'The Cole family',
      scheduleTitle: 'Come for the vows, stay for the dancing',
      scheduleItems: [
        { time: '5:00 PM', title: 'Ceremony', detail: 'The garden' },
        { time: '6:30 PM', title: 'Dinner', detail: 'The orangery' },
        { time: '9:00 PM', title: 'Dancing', detail: 'Under the stars' },
      ],
      rsvpTitle: 'Will you join us?',
      rsvpBody: 'Kindly let us know by 30 August 2026.',
      faqTitle: 'A few useful notes',
      faqItems: [
        { question: 'What should I wear?', answer: 'Garden formal, made for an evening outdoors.' },
        { question: 'Can I bring a plus one?', answer: 'Your invitation will note the seats saved for you.' },
      ],
      giftsTitle: 'Your presence is enough',
      giftsBody: 'If you would like to give a little something, our gift list is available here.',
      galleryTitle: 'Made of little moments',
      galleryBody: 'A few favourites from the road that brought us here.',
      footerNote: 'We cannot wait to celebrate with you.',
    },
    defaultSections: ['story', 'schedule', 'rsvp', 'faq', 'gallery'],
  },
  {
    id: 'birthday',
    label: 'Birthday',
    glyph: '✦',
    hint: 'Another trip around the sun',
    titleLabel: 'Celebrant & milestone',
    titlePlaceholder: 'Maya turns 30',
    sectionLabels: {
      story: 'The reason',
      schedule: 'The plan',
      rsvp: 'Save your spot',
      faq: 'Party notes',
      gallery: 'Good times',
    },
    defaults: {
      title: 'Maya turns 30',
      eyebrow: 'Another trip around the sun',
      intro: 'Come for golden hour, stay for cake',
      date: '2026-10-03',
      time: '18:30',
      venue: 'Luna Rooftop',
      location: 'Limassol, Cyprus',
      storyTitle: 'Thirty, thriving & ready to dance',
      storyBody:
        'There are too many good people and stories to fit around one table—so we are taking over the rooftop. Bring your favourite memory and your dancing shoes.',
      hostOneLabel: '',
      hostOne: '',
      hostTwoLabel: '',
      hostTwo: '',
      scheduleTitle: 'Here is the plan',
      scheduleItems: [
        { time: '6:30 PM', title: 'Golden hour drinks', detail: 'Rooftop terrace' },
        { time: '8:00 PM', title: 'Dinner & cake', detail: 'Long table' },
        { time: '9:30 PM', title: 'Dance floor', detail: 'Requests welcome' },
      ],
      rsvpTitle: 'Save your spot',
      rsvpBody: 'Tell us you are coming by 20 September.',
      faqTitle: 'The party details',
      faqItems: [
        { question: 'What is the dress code?', answer: 'Colourful, celebratory and entirely you.' },
        { question: 'Should I bring anything?', answer: 'Just your best story about Maya.' },
      ],
      giftsTitle: 'No presents, please',
      giftsBody: 'Your company is the whole gift. Truly.',
      galleryTitle: 'Good times, documented',
      galleryBody: 'A little evidence of the adventures so far.',
      footerNote: 'See you on the dance floor.',
    },
    defaultSections: ['story', 'schedule', 'rsvp', 'faq', 'gallery'],
  },
  {
    id: 'baby-shower',
    label: 'Baby shower',
    glyph: '◡',
    hint: 'For a tiny new beginning',
    titleLabel: 'Celebration title',
    titlePlaceholder: 'A little wildflower is on the way',
    sectionLabels: {
      story: 'A little note',
      schedule: 'The afternoon',
      rsvp: 'RSVP',
      faq: 'Helpful details',
      gallery: 'Growing family',
    },
    defaults: {
      title: 'A little wildflower is on the way',
      eyebrow: 'Please join us for a baby shower',
      intro: 'Celebrating Emma, Noah & their newest adventure',
      date: '2026-11-08',
      time: '14:00',
      venue: 'The Garden Room',
      location: 'Larnaca, Cyprus',
      storyTitle: 'A tiny new beginning',
      storyBody:
        'Our family is growing by two little feet. Join us for a gentle afternoon of lunch, happy tears and all the love already waiting for this little one.',
      hostOneLabel: '',
      hostOne: '',
      hostTwoLabel: '',
      hostTwo: '',
      scheduleTitle: 'An easy afternoon together',
      scheduleItems: [
        { time: '2:00 PM', title: 'Welcome lunch', detail: 'The garden room' },
        { time: '3:30 PM', title: 'Games & wishes', detail: 'Bring one for baby' },
        { time: '4:30 PM', title: 'Tea & cake', detail: 'Sweet things' },
      ],
      rsvpTitle: 'Can you make it?',
      rsvpBody: 'Please reply by 25 October so we can save you a seat.',
      faqTitle: 'Good to know',
      faqItems: [
        { question: 'Is this a surprise?', answer: 'Not this time—Emma and Noah are happily counting down.' },
        { question: 'Can children come?', answer: 'Little guests are very welcome.' },
      ],
      giftsTitle: 'For the little one',
      giftsBody: 'We have made a small registry with a few useful things for the new arrival.',
      galleryTitle: 'The family is growing',
      galleryBody: 'A few snapshots before our newest favourite person arrives.',
      footerNote: 'Made with love for the smallest guest of honour.',
    },
    defaultSections: ['story', 'schedule', 'rsvp', 'faq'],
  },
  {
    id: 'engagement',
    label: 'Engagement',
    glyph: '◇',
    hint: 'They said yes',
    titleLabel: 'Your names',
    titlePlaceholder: 'Amelia & Theo',
    sectionLabels: {
      story: 'The yes',
      schedule: 'The evening',
      rsvp: 'RSVP',
      faq: 'Good to know',
      gallery: 'Us, lately',
    },
    defaults: {
      title: 'Amelia & Theo',
      eyebrow: 'We said yes',
      intro: 'Now it is time to celebrate',
      date: '2026-08-29',
      time: '19:00',
      venue: 'Mare House',
      location: 'Paphos, Cyprus',
      storyTitle: 'The easiest yes',
      storyBody:
        'One sunset, one very important question, and the beginning of everything next. Come raise a glass with us before the planning really begins.',
      hostOneLabel: '',
      hostOne: '',
      hostTwoLabel: '',
      hostTwo: '',
      scheduleTitle: 'Drinks, dinner, then whatever happens',
      scheduleItems: [
        { time: '7:00 PM', title: 'Welcome drinks', detail: 'Sea terrace' },
        { time: '8:30 PM', title: 'Shared dinner', detail: 'Courtyard table' },
        { time: '10:00 PM', title: 'Music & dancing', detail: 'Barefoot encouraged' },
      ],
      rsvpTitle: 'Raise a glass with us',
      rsvpBody: 'Let us know by 12 August if you can be there.',
      faqTitle: 'A few useful things',
      faqItems: [
        { question: 'Where can I park?', answer: 'Valet parking is available at the entrance.' },
        { question: 'Is dinner included?', answer: 'Absolutely—come hungry.' },
      ],
      giftsTitle: 'No gifts needed',
      giftsBody: 'Having our favourite people in one place is more than enough.',
      galleryTitle: 'Us, lately',
      galleryBody: 'Life before the question—and the very happy after.',
      footerNote: 'Here is to everything next.',
    },
    defaultSections: ['story', 'schedule', 'rsvp', 'faq', 'gallery'],
  },
  {
    id: 'graduation',
    label: 'Graduation',
    glyph: '↗',
    hint: 'A very good next chapter',
    titleLabel: 'Graduate & degree',
    titlePlaceholder: 'Alex did it!',
    sectionLabels: {
      story: 'The milestone',
      schedule: 'The celebration',
      rsvp: 'RSVP',
      faq: 'Good to know',
      gallery: 'The journey',
    },
    defaults: {
      title: 'Alex did it!',
      eyebrow: 'Class of 2026',
      intro: 'The late nights paid off—come celebrate',
      date: '2026-07-18',
      time: '17:30',
      venue: 'The Workshop',
      location: 'Nicosia, Cyprus',
      storyTitle: 'One chapter closed. A brilliant one next.',
      storyBody:
        'After four years, too much coffee and more group projects than anyone deserves, the degree is finally framed. Let us celebrate the work and what comes next.',
      hostOneLabel: '',
      hostOne: '',
      hostTwoLabel: '',
      hostTwo: '',
      scheduleTitle: 'Caps off, glasses up',
      scheduleItems: [
        { time: '5:30 PM', title: 'Welcome drinks', detail: 'Courtyard' },
        { time: '7:00 PM', title: 'Dinner & speeches', detail: 'Main table' },
        { time: '9:00 PM', title: 'Music', detail: 'No studying allowed' },
      ],
      rsvpTitle: 'Join the celebration',
      rsvpBody: 'Please reply by 5 July.',
      faqTitle: 'The useful details',
      faqItems: [
        { question: 'Can family come?', answer: 'Of course—just include everyone in your reply.' },
        { question: 'Is there parking?', answer: 'Free parking is available across from the venue.' },
      ],
      giftsTitle: 'Cheering is plenty',
      giftsBody: 'No gifts expected. A book recommendation for the next chapter is always welcome.',
      galleryTitle: 'How we got here',
      galleryBody: 'Some highlights, questionable haircuts and very late library nights.',
      footerNote: 'Onward and upward.',
    },
    defaultSections: ['story', 'schedule', 'rsvp', 'faq', 'gallery'],
  },
  {
    id: 'dinner',
    label: 'Dinner party',
    glyph: '⌁',
    hint: 'A table worth gathering around',
    titleLabel: 'Dinner title',
    titlePlaceholder: 'A midsummer supper',
    sectionLabels: {
      story: 'The invitation',
      schedule: 'The menu',
      rsvp: 'Your place',
      faq: 'Table notes',
      gallery: 'Last time',
    },
    defaults: {
      title: 'A midsummer supper',
      eyebrow: 'One long table. One warm night.',
      intro: 'You are invited to dinner in the garden',
      date: '2026-06-20',
      time: '19:30',
      venue: 'The Courtyard',
      location: 'Nicosia, Cyprus',
      storyTitle: 'Dinner tastes better together',
      storyBody:
        'We are setting a long table outside and cooking the things we love most. Come slowly, stay late and let us make a proper evening of it.',
      hostOneLabel: '',
      hostOne: '',
      hostTwoLabel: '',
      hostTwo: '',
      scheduleTitle: 'From aperitivo to something sweet',
      scheduleItems: [
        { time: '7:30 PM', title: 'Aperitivo', detail: 'Under the lemon tree' },
        { time: '8:30 PM', title: 'Supper', detail: 'Family style' },
        { time: '10:30 PM', title: 'Dessert', detail: 'And one more bottle' },
      ],
      rsvpTitle: 'We are saving you a place',
      rsvpBody: 'Reply by 12 June and include any dietary notes.',
      faqTitle: 'Around the table',
      faqItems: [
        { question: 'What can I bring?', answer: 'Nothing at all—unless you have a favourite bottle to share.' },
        { question: 'What should I wear?', answer: 'Easy summer evening things.' },
      ],
      giftsTitle: 'Bring only an appetite',
      giftsBody: 'We have the rest covered.',
      galleryTitle: 'Around this table',
      galleryBody: 'A few scenes from dinners gone by.',
      footerNote: 'Come hungry. Leave late.',
    },
    defaultSections: ['story', 'schedule', 'rsvp', 'faq'],
  },
]

export const templates = [
  {
    id: 'classic',
    name: 'Sunday Paper',
    personality: 'Warm & editorial',
    description: 'Airy typography, tactile paper tones and quiet details.',
    price: 39,
    palette: ['#f2ede5', '#2d2925', '#c99a77'],
  },
  {
    id: 'modern',
    name: 'Studio No. 4',
    personality: 'Bold & minimal',
    description: 'An expressive grid for people who like things crisp.',
    price: 39,
    palette: ['#e8eadf', '#1e201d', '#f4f1ea'],
  },
  {
    id: 'playful',
    name: 'Picnic Confetti',
    personality: 'Joyful & colourful',
    description: 'Soft colour, happy shapes and a little bit of mischief.',
    price: 39,
    palette: ['#f6eee5', '#dc856d', '#f2cc6d'],
  },
  {
    id: 'luxury',
    name: 'Moonlit Silk',
    personality: 'Elegant & cinematic',
    description: 'Deep ink, luminous type and understated ceremony.',
    price: 49,
    palette: ['#242321', '#e7dac4', '#a58a63'],
  },
]

export function getOccasion(id) {
  return occasions.find((occasion) => occasion.id === id) ?? occasions[0]
}

export function getTemplate(id) {
  return templates.find((template) => template.id === id) ?? templates[0]
}

export function formatEventDate(value, locale = 'en-GB') {
  if (!/^\d{4}-\d{2}-\d{2}$/.test(value ?? '')) return 'Choose a date'

  return new Intl.DateTimeFormat(locale, {
    weekday: 'long',
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  }).format(new Date(`${value}T12:00:00`))
}

export function formatTime(value) {
  if (!/^\d{2}:\d{2}$/.test(value ?? '')) return 'Choose a time'
  const [hours, minutes] = value.split(':').map(Number)
  return new Intl.DateTimeFormat('en-GB', {
    hour: 'numeric',
    minute: '2-digit',
    hour12: true,
  }).format(new Date(2026, 0, 1, hours, minutes))
}
