export const WEDDING_DATE = '2026-09-19T17:00:00+03:00'

export const mapLinks = {
  bride: 'https://www.google.com/maps/search/?api=1&query=Strovolos%2C+Cyprus',
  groom: 'https://www.google.com/maps/search/?api=1&query=Engomi%2C+Cyprus',
  church:
    'https://www.google.com/maps/search/?api=1&query=Panagia+Chryseleousa+Church%2C+Strovolos%2C+Cyprus',
  venue:
    'https://www.google.com/maps/search/?api=1&query=Aelia+Wellness+Retreat%2C+Analiontas%2C+Cyprus',
}

export const translations = {
  en: {
    language: 'Language',
    skip: 'Skip to content',
    pageTitle: 'Andreas & Eleni — 19.09.2026',
    pageDescription: 'Celebrate the wedding of Andreas and Eleni in Cyprus on September 19, 2026.',
    names: 'Andreas & Eleni',
    date: 'Saturday, 19 September 2026 · 5:00 PM',
    heroAlt: 'Andreas and Eleni walking through a Mediterranean estate garden',
    countdownEyebrow: 'Until we say “I do”',
    countdownDone: 'Today is the day',
    countdownPast: 'Thank you for celebrating with us',
    units: ['Days', 'Hours', 'Minutes', 'Seconds'],
    calendar: 'Add to calendar',
    calendarEvent: 'The wedding of Andreas & Eleni',
    calendarDescription: 'Wedding ceremony followed by dinner and drinks.',
    invitationEyebrow: 'Together with our families',
    invitationTitle: 'We would love for you to be there.',
    invitationText:
      'With full hearts, we invite you to celebrate the beginning of our life together. Having you beside us will make this day even more meaningful.',
    parentsTitle: 'Our parents',
    brideParentsLabel: 'Parents of the bride',
    brideParents: 'George & Maria Nicolaou',
    groomParentsLabel: 'Parents of the groom',
    groomParents: 'Christos & Anna Georgiou',
    timelineEyebrow: 'September 19, 2026',
    timelineTitle: 'The day',
    timelineIntro: 'A little guide to every part of our celebration.',
    map: 'Open in Google Maps',
    timeline: [
      {
        time: '2:00 PM',
        title: 'Bride’s preparations',
        place: 'Eleni’s family home',
        address: 'Strovolos, Nicosia',
        map: mapLinks.bride,
      },
      {
        time: '2:30 PM',
        title: 'Groom’s preparations',
        place: 'Andreas’s family home',
        address: 'Engomi, Nicosia',
        map: mapLinks.groom,
      },
      {
        time: '5:00 PM',
        title: 'Wedding ceremony',
        place: 'Panagia Chryseleousa Church',
        address: 'Strovolos, Nicosia',
        map: mapLinks.church,
      },
      {
        time: '7:00 PM',
        title: 'Reception · dinner & drinks',
        place: 'Aelia Wellness Retreat',
        address: 'Analiontas, Nicosia',
        map: mapLinks.venue,
      },
    ],
    rsvpEyebrow: 'Kindly reply',
    rsvpTitle: 'Will you celebrate with us?',
    rsvpDeadline: 'Please reply by 30 August 2026.',
    attending: 'Joyfully accepts',
    declining: 'Regretfully declines',
    name: 'Full name',
    namePlaceholder: 'Your name',
    contact: 'Email or phone',
    contactPlaceholder: 'you@example.com or +357…',
    contactError: 'Add a valid email address or phone number.',
    guests: 'Number attending, including you',
    decreaseGuests: 'Decrease guest count',
    increaseGuests: 'Increase guest count',
    message: 'Message for the couple',
    optional: 'Optional',
    messagePlaceholder: 'Share a note, dietary needs, or anything we should know…',
    submit: 'Send RSVP',
    rsvpSuccessTitle: 'Thank you, we have your reply.',
    rsvpSuccessText: 'We cannot wait to celebrate this beautiful day with you.',
    rsvpDeclineText: 'We will miss you, and we are grateful you let us know.',
    editResponse: 'Edit response',
    requiredError: 'Please add your name and contact information.',
    guestError: 'Please choose between 1 and 12 guests.',
    privacy: 'Your details will be used only to plan the wedding.',
    contactTitle: 'Need a little help?',
    contactText: 'You can reach either of us with any question before the day.',
    faqEyebrow: 'Good to know',
    faqTitle: 'Frequently asked questions',
    faqs: [
      {
        title: 'Where can I park?',
        body: 'Free parking is available beside the church and on-site at the venue. Follow the signs and attendants when you arrive.',
      },
      {
        title: 'How do I travel between locations?',
        body: 'The church and reception are approximately 25 minutes apart by car. We recommend pre-booking a taxi for the return journey. Contact us if you need help arranging transport.',
      },
      {
        title: 'Where should I stay?',
        body: 'Suggested starting points in central Nicosia are MAP Boutique Hotel, The Classic Hotel, and Gate Twenty Two. Please book directly; no rooms are being held.',
      },
      {
        title: 'What is the dress code?',
        body: 'Formal evening attire with a relaxed garden feel. Soft neutrals and muted colours are welcome; please reserve white and ivory for the bride. The venue has stone paths, so block heels or flats are most comfortable.',
      },
    ],
    galleryEyebrow: 'Our shared album',
    galleryTitle: 'Share the moments',
    galleryText:
      'Captured something special? Add your photos and short videos to this wedding-day slideshow.',
    galleryAlt: [
      'Andreas and Eleni walking through a Mediterranean estate garden',
      'An elegant wedding dinner table at sunset',
      'Two wedding rings resting on pale limestone',
    ],
    carousel: 'slideshow',
    previous: 'Previous photo',
    next: 'Next photo',
    pause: 'Pause slideshow',
    play: 'Play slideshow',
    slideOf: 'of',
    uploadTitle: 'Add your view of the day',
    uploadText: 'Drop photos or short videos here, or choose them from your device.',
    uploadButton: 'Choose photos or videos',
    uploadHint: 'JPG, PNG, WebP, MP4 or WebM · up to 50 MB each',
    uploadAdded: 'Added to your local slideshow preview.',
    uploadError: 'Choose image or video files under 50 MB.',
    remove: 'Remove',
    moderation: 'A connected gallery service is required to publish guest uploads.',
    footerDate: '19 · 09 · 2026',
    footerText: 'Made with love in Cyprus',
  },
  el: {
    language: 'Γλώσσα',
    skip: 'Μετάβαση στο περιεχόμενο',
    pageTitle: 'Ανδρέας & Ελένη — 19.09.2026',
    pageDescription: 'Γιορτάστε μαζί μας τον γάμο του Ανδρέα και της Ελένης στην Κύπρο στις 19 Σεπτεμβρίου 2026.',
    names: 'Ανδρέας & Ελένη',
    date: 'Σάββατο, 19 Σεπτεμβρίου 2026 · 17:00',
    heroAlt: 'Ο Ανδρέας και η Ελένη περπατούν σε έναν μεσογειακό κήπο',
    countdownEyebrow: 'Μέχρι να πούμε το «ναι»',
    countdownDone: 'Η μεγάλη μέρα έφτασε',
    countdownPast: 'Ευχαριστούμε που γιορτάσατε μαζί μας',
    units: ['Ημέρες', 'Ώρες', 'Λεπτά', 'Δευτερόλεπτα'],
    calendar: 'Προσθήκη στο ημερολόγιο',
    calendarEvent: 'Ο γάμος του Ανδρέα και της Ελένης',
    calendarDescription: 'Μυστήριο γάμου και στη συνέχεια δείπνο και ποτό.',
    invitationEyebrow: 'Μαζί με τις οικογένειές μας',
    invitationTitle: 'Θα χαρούμε πολύ να είστε μαζί μας.',
    invitationText:
      'Με τις καρδιές μας γεμάτες χαρά, σας προσκαλούμε να γιορτάσετε μαζί μας την αρχή της κοινής μας ζωής. Η παρουσία σας θα κάνει αυτή τη μέρα ακόμη πιο ξεχωριστή.',
    parentsTitle: 'Οι γονείς μας',
    brideParentsLabel: 'Γονείς της νύφης',
    brideParents: 'Γιώργος & Μαρία Νικολάου',
    groomParentsLabel: 'Γονείς του γαμπρού',
    groomParents: 'Χρίστος & Άννα Γεωργίου',
    timelineEyebrow: '19 Σεπτεμβρίου 2026',
    timelineTitle: 'Η ημέρα μας',
    timelineIntro: 'Ένας μικρός οδηγός για κάθε στιγμή της γιορτής μας.',
    map: 'Άνοιγμα στους Χάρτες Google',
    timeline: [
      {
        time: '14:00',
        title: 'Αλλάματα νύφης',
        place: 'Το πατρικό της Ελένης',
        address: 'Στρόβολος, Λευκωσία',
        map: mapLinks.bride,
      },
      {
        time: '14:30',
        title: 'Αλλάματα γαμπρού',
        place: 'Το πατρικό του Ανδρέα',
        address: 'Έγκωμη, Λευκωσία',
        map: mapLinks.groom,
      },
      {
        time: '17:00',
        title: 'Μυστήριο γάμου',
        place: 'Ιερός Ναός Παναγίας Χρυσελεούσας',
        address: 'Στρόβολος, Λευκωσία',
        map: mapLinks.church,
      },
      {
        time: '19:00',
        title: 'Δεξίωση · φαγητό & ποτό',
        place: 'Aelia Wellness Retreat',
        address: 'Αναλιόντας, Λευκωσία',
        map: mapLinks.venue,
      },
    ],
    rsvpEyebrow: 'Παρακαλούμε απαντήστε',
    rsvpTitle: 'Θα γιορτάσετε μαζί μας;',
    rsvpDeadline: 'Παρακαλούμε απαντήστε έως τις 30 Αυγούστου 2026.',
    attending: 'Με χαρά θα παρευρεθώ',
    declining: 'Δυστυχώς δεν θα μπορέσω',
    name: 'Ονοματεπώνυμο',
    namePlaceholder: 'Το όνομά σας',
    contact: 'Email ή τηλέφωνο',
    contactPlaceholder: 'you@example.com ή +357…',
    contactError: 'Συμπληρώστε ένα έγκυρο email ή τηλέφωνο.',
    guests: 'Αριθμός ατόμων, μαζί με εσάς',
    decreaseGuests: 'Μείωση αριθμού καλεσμένων',
    increaseGuests: 'Αύξηση αριθμού καλεσμένων',
    message: 'Μήνυμα για το ζευγάρι',
    optional: 'Προαιρετικό',
    messagePlaceholder: 'Γράψτε μια ευχή, διατροφικές ανάγκες ή οτιδήποτε πρέπει να γνωρίζουμε…',
    submit: 'Αποστολή απάντησης',
    rsvpSuccessTitle: 'Ευχαριστούμε, λάβαμε την απάντησή σας.',
    rsvpSuccessText: 'Ανυπομονούμε να γιορτάσουμε μαζί σας αυτή την ξεχωριστή μέρα.',
    rsvpDeclineText: 'Θα μας λείψετε και σας ευχαριστούμε που μας ενημερώσατε.',
    editResponse: 'Επεξεργασία απάντησης',
    requiredError: 'Παρακαλούμε συμπληρώστε το όνομα και τα στοιχεία επικοινωνίας σας.',
    guestError: 'Παρακαλούμε επιλέξτε από 1 έως 12 άτομα.',
    privacy: 'Τα στοιχεία σας θα χρησιμοποιηθούν μόνο για την οργάνωση του γάμου.',
    contactTitle: 'Χρειάζεστε βοήθεια;',
    contactText: 'Μπορείτε να επικοινωνήσετε μαζί μας για οποιαδήποτε ερώτηση πριν από τη μεγάλη μέρα.',
    faqEyebrow: 'Χρήσιμες πληροφορίες',
    faqTitle: 'Συχνές ερωτήσεις',
    faqs: [
      {
        title: 'Πού μπορώ να σταθμεύσω;',
        body: 'Υπάρχει δωρεάν χώρος στάθμευσης δίπλα στην εκκλησία και εντός του χώρου δεξίωσης. Ακολουθήστε τη σήμανση και τις οδηγίες των υπευθύνων κατά την άφιξη.',
      },
      {
        title: 'Πώς θα μετακινηθώ μεταξύ των χώρων;',
        body: 'Η εκκλησία και ο χώρος δεξίωσης απέχουν περίπου 25 λεπτά με αυτοκίνητο. Προτείνουμε να κλείσετε ταξί εκ των προτέρων για την επιστροφή. Επικοινωνήστε μαζί μας αν χρειάζεστε βοήθεια με τη μεταφορά.',
      },
      {
        title: 'Πού μπορώ να μείνω;',
        body: 'Για διαμονή στο κέντρο της Λευκωσίας, μπορείτε να δείτε τα MAP Boutique Hotel, The Classic Hotel και Gate Twenty Two. Η κράτηση γίνεται απευθείας με το ξενοδοχείο και δεν υπάρχουν δεσμευμένα δωμάτια.',
      },
      {
        title: 'Ποιο είναι το dress code;',
        body: 'Επίσημο βραδινό ντύσιμο με κομψή, υπαίθρια αισθητική. Οι απαλοί ουδέτεροι και γήινοι τόνοι είναι ευπρόσδεκτοι· παρακαλούμε αφήστε το λευκό και το ιβουάρ για τη νύφη. Ο χώρος έχει πέτρινα μονοπάτια, οπότε προτιμήστε άνετα παπούτσια.',
      },
    ],
    galleryEyebrow: 'Το κοινό μας άλμπουμ',
    galleryTitle: 'Μοιραστείτε τις στιγμές',
    galleryText:
      'Απαθανατίσατε μια ξεχωριστή στιγμή; Προσθέστε τις φωτογραφίες και τα σύντομα βίντεό σας σε αυτό το slideshow.',
    galleryAlt: [
      'Ο Ανδρέας και η Ελένη περπατούν σε έναν μεσογειακό κήπο',
      'Ένα κομψό γαμήλιο τραπέζι στο ηλιοβασίλεμα',
      'Δύο βέρες πάνω σε ανοιχτόχρωμη πέτρα',
    ],
    carousel: 'παρουσίαση διαφανειών',
    previous: 'Προηγούμενη φωτογραφία',
    next: 'Επόμενη φωτογραφία',
    pause: 'Παύση slideshow',
    play: 'Αναπαραγωγή slideshow',
    slideOf: 'από',
    uploadTitle: 'Προσθέστε τη δική σας ματιά',
    uploadText: 'Σύρετε φωτογραφίες ή σύντομα βίντεο εδώ ή επιλέξτε τα από τη συσκευή σας.',
    uploadButton: 'Επιλέξτε φωτογραφίες ή βίντεο',
    uploadHint: 'JPG, PNG, WebP, MP4 ή WebM · έως 50 MB το καθένα',
    uploadAdded: 'Προστέθηκε στην τοπική προεπισκόπηση του slideshow.',
    uploadError: 'Επιλέξτε αρχεία εικόνας ή βίντεο έως 50 MB.',
    remove: 'Αφαίρεση',
    moderation: 'Απαιτείται σύνδεση με υπηρεσία gallery για τη δημοσίευση των αρχείων.',
    footerDate: '19 · 09 · 2026',
    footerText: 'Με αγάπη από την Κύπρο',
  },
}
